# Знакомство с PyTorch

Сейчас мы познакомимся с библиотекой *PyTorch*. Он очень похож на *NumPy*, и сейчас вы в этом убедитесь!

А почему именно *PyTorch*? Почитать можно [здесь](https://habr.com/ru/post/334380/).

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Вспоминаем *NumPy* и сравниваем операции в *PyTorch*

Мы можем создавать матрицы, перемножать их, складывать, транспонировать и в целом совершать любые матричные операции

In [ ]:
import numpy as np

import torch
import torchvision

import torch.nn as nn
import torch.nn.functional as F

import matplotlib.pyplot as plt

In [ ]:
np.random.seed(42)

a = np.random.rand(5, 3) # создали случайную матрицу 
a

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [ ]:
print("Проверили размеры : %s\n" % (a.shape,))

Проверили размеры : (5, 3)



In [ ]:
print("Добавили 5 :\n%s\n" % (a + 5))

Добавили 5 :
[[5.37454012 5.95071431 5.73199394]
 [5.59865848 5.15601864 5.15599452]
 [5.05808361 5.86617615 5.60111501]
 [5.70807258 5.02058449 5.96990985]
 [5.83244264 5.21233911 5.18182497]]



## Задание

Умножьте матрицу `а` на транспонированную матрицу `а`.  

Чему равен самый первый элемент результата?  
Ответ округлите до сотых.

In [ ]:
# your code here
round(a.dot(a.T)[0][0], 2)

1.58

In [ ]:
print("Среднее по колонкам :\n%s\n" % (a.mean(axis=-1)))

Среднее по колонкам :
[0.68574946 0.30355721 0.50845826 0.56618897 0.40886891]



In [ ]:
print("Изменили размеры :\n%s\n" % (a.reshape(3, 5).shape,))

Изменили размеры :
(3, 5)



## Задание

При помощи *NumPy* посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [ ]:
# your code here
(np.arange(1, 10001) ** 2).sum()

333383335000

Аналогичные операции в *PyTorch* выглядят следующим образом, синтаксис отличается, но совсем немного:

In [ ]:
x = torch.rand(5, 3)
x

tensor([[0.6408, 0.1482, 0.5931],
        [0.9692, 0.0730, 0.2023],
        [0.5263, 0.6669, 0.5399],
        [0.8284, 0.2393, 0.4231],
        [0.4793, 0.0440, 0.6963]])

In [ ]:
print("Проверили размеры : %s\n" % (x.shape,))

Проверили размеры : torch.Size([5, 3])



In [ ]:
print("Добавили 5 :\n%s\n" % (x + 5))

Добавили 5 :
tensor([[5.6408, 5.1482, 5.5931],
        [5.9692, 5.0730, 5.2023],
        [5.5263, 5.6669, 5.5399],
        [5.8284, 5.2393, 5.4231],
        [5.4793, 5.0440, 5.6963]])



In [ ]:
print("X*X^T  (1):\n%s\n" % (torch.matmul(x, x.transpose(1, 0))))
print("X*X^T  (2):\n%s\n" % (x.mm(x.t())))

X*X^T  (1):
tensor([[0.7843, 0.7518, 0.7563, 0.8172, 0.7266],
        [0.7518, 0.9856, 0.6680, 0.9059, 0.6086],
        [0.7563, 0.6680, 1.0133, 0.8240, 0.6576],
        [0.8172, 0.9059, 0.8240, 0.9225, 0.7022],
        [0.7266, 0.6086, 0.6576, 0.7022, 0.7165]])

X*X^T  (2):
tensor([[0.7843, 0.7518, 0.7563, 0.8172, 0.7266],
        [0.7518, 0.9856, 0.6680, 0.9059, 0.6086],
        [0.7563, 0.6680, 1.0133, 0.8240, 0.6576],
        [0.8172, 0.9059, 0.8240, 0.9225, 0.7022],
        [0.7266, 0.6086, 0.6576, 0.7022, 0.7165]])



In [ ]:
print("Среднее по колонкам :\n%s\n" % (x.mean(dim=-1)))

Среднее по колонкам :
tensor([0.4607, 0.4148, 0.5777, 0.4969, 0.4065])



In [ ]:
print("Изменили размеры :\n%s\n" % (x.view([3, 5]).shape,))
print("Изменили размеры :\n%s\n" % (x.view_as(x.t()).shape,))

Изменили размеры :
torch.Size([3, 5])

Изменили размеры :
torch.Size([3, 5])



Небольшой пример того, как меняются операции:

* `x.reshape([1,2,8]) -> x.view(1,2,8)`

* `x.sum(axis=-1) -> x.sum(dim=-1)`

* `x.astype('int64') -> x.type(torch.LongTensor)`

Для помощи вам есть [таблица](https://github.com/torch/torch7/wiki/Torch-for-Numpy-users), которая поможет вам найти аналог операции в *NumPy*.


При помощи *PyTorch* посчитаем сумму квадратов натуральных чисел от 1 до 10000.

In [ ]:
torch.sum(torch.range(1, 10000) ** 2)

<ipython-input-30-b9d129fd8adb>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.sum(torch.range(1, 10000) ** 2)


tensor(3.3338e+11)

Создаем тензоры в *PyTorch* и снова изучаем базовые операции

In [ ]:
x = torch.empty(5, 3) # пустой тензор
print(x)

tensor([[ 4.3153e-35,  0.0000e+00,  4.0154e-36],
        [ 0.0000e+00, -2.0665e-20,  4.5650e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [ ]:
x = torch.rand(5, 3) # тензор со случайными числами
print(x)

tensor([[0.1852, 0.2873, 0.9859],
        [0.4756, 0.1163, 0.0739],
        [0.8151, 0.2256, 0.8965],
        [0.2229, 0.0137, 0.1551],
        [0.3737, 0.6374, 0.5873]])


In [ ]:
x = torch.zeros(5, 3, dtype=torch.long) # тензор с нулями и указанием типов чисел
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x = torch.tensor([5.5, 3]) # конструируем тензор из питоновского листа
print(x)

tensor([5.5000, 3.0000])


In [ ]:
x = x.new_ones(5, 3, dtype=torch.double) # используем уже созданный тензор для создания тензора из единичек
print(x, x.size()) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.Size([5, 3])


In [ ]:
x = torch.randn_like(x, dtype=torch.float) # создаем матрицу с размерами как у x
print(x, x.size())

tensor([[ 0.7756, -1.1803, -1.1490],
        [-1.1812, -0.0097, -0.8545],
        [-0.1057, -0.9342, -1.0155],
        [-0.4593,  0.0800,  0.6947],
        [ 1.5869,  0.4845,  0.9315]]) torch.Size([5, 3])


## Задание

Сгенерируйте два тензора: `x` и `y` размера 5 на 3 со случайными числами.
Вычислите сумму тензоров `x` и `y`.

В ответе напишите значение первой координаты в полученной суммы, округленной до сотых.

In [ ]:
torch.manual_seed(42)

# your code here
x = torch.rand(5, 3)
y = torch.rand(5, 3)
torch.round((x + y)[0, 0], decimals=2)

tensor(1.3100)

In [ ]:
print(x * y) # поэлементное умножение

tensor([[0.3789, 0.8102, 0.2197],
        [0.2557, 0.2450, 0.1620],
        [0.1132, 0.2356, 0.7824],
        [0.0140, 0.2519, 0.2130],
        [0.1733, 0.3106, 0.0046]])


## Задание

Умножьте матрицу `x` на транспонированную матрицу `y`.

В ответ напишите последний элемент (правый нижний) полученной матрицы.  
Ответ округлите до сотых.

In [ ]:
# your code here
torch.round(x.mm(y.t())[-1, -1], decimals=2)

tensor(0.4900)

In [ ]:
print(x.unsqueeze(0).shape) # добавили измерение в начало, аналог броадкастинга 

torch.Size([1, 5, 3])


In [ ]:
print(x.unsqueeze(0).squeeze(0).shape) # убрали измерение в начале, аналог броадкастинга 

torch.Size([5, 3])


In [ ]:
a = torch.rand((1,3))
a

tensor([[0.9516, 0.0753, 0.8860]])

In [ ]:
a.squeeze(0)

tensor([0.9516, 0.0753, 0.8860])

Мы также можем делать обычные срезы и переводить матрицы назад в *NumPy*:

In [ ]:
a = np.ones((3, 5))
x = torch.ones((3, 5))
print(np.allclose(x.numpy(), a))
print(np.allclose(x.numpy()[:, 1], a[:, 1]))

True
True


In [ ]:
a = np.array([1,2,3,4])
b = np.array([[5],[6],[7],[8]])

a.shape, b.shape

((4,), (4, 1))

In [ ]:
a @ b

array([70])

In [ ]:
b @ a

ValueError: ignored