# Знакомство с PyTorch

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Введение

Библиотека PyTorch является универсальным инструментом машинного обучения. Она популярна работе с нейронными сетями. Является open-source проектом. В библиотеке есть четыре ключевых составляющих:

* Развитый инструментарий для работы с тензорами. Он похож на numpy, но даёт дополнительные возможности по контролю выделяемой памяти, что важно при работе с большими моделями и данными.

* Простое построение динамического вычислительного графа, позволяющего получать градиенты целевых функций от параметров модели.

* Большой набор готовых слоёв для построения нейронных сетей произвольной архитектуры.

* Возможность перенаправлять вычисления на графические процессоры GPU.


In [ ]:
import torch
 
e  = torch.eye(3) # единичная матрица 3x3
print(e) 

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## Тензоры

Тензор - это основной объект в *PyTorch*. Тензоры схожи с *ndarrays* в *NumPy*, с добавлением того, что тензоры могут быть использованы на GPU для ускорения вычислений.

* Тензор - это набор из элементов одного типа. 
* Тензоры могут быть одномерные (векторы), двумерные (матрицы), трехмерные и так далее - любой размерности.

In [ ]:
a = torch.rand(5, 3) # сгенерировали матрицу 5x3 из случайных чисел
a

tensor([[0.0303, 0.9512, 0.1059],
        [0.5574, 0.0938, 0.6646],
        [0.8345, 0.9677, 0.4832],
        [0.8341, 0.2771, 0.5499],
        [0.5778, 0.7791, 0.5909]])

In [ ]:
a.shape # посмотрели размеры

torch.Size([5, 3])

In [ ]:
a + 3 # добавили 3 ко всем элементам

tensor([[3.3089, 3.9618, 3.1672],
        [3.2231, 3.5418, 3.2646],
        [3.0355, 3.6424, 3.1923],
        [3.6987, 3.5001, 3.6931],
        [3.0327, 3.4032, 3.3457]])

## Вычисления на видеокарте

Если на компьютере есть графическая карта, то можно осуществлять вычисления на ней - обычно это ускоряет вычисления в разы.

Проведем эксперимент:
1. Сначала создадим две единичных матрицы большой размерности и перемножим их как обычно, используя мощности центрального процессора (CPU), засечем время.

2. Затем создадим такие же тензоры, перенесем их на GPU, там сделаем умножение и вернем результат на CPU (можно сразу создавать тензоры на GPU, но обычно придерживаются первого варианта). Также замерим время и сравним.

**Первый вариант (CPU)**

In [ ]:
%%time

x1 = torch.eye(10000)
y1 = torch.eye(10000)
z1 = x1.mm(y1)   

CPU times: user 27.1 s, sys: 499 ms, total: 27.6 s
Wall time: 27.7 s


**Второй вариант (GPU)**

In [ ]:
cpu = torch.device("cpu")
gpu = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
g

In [ ]:
%%time

x1 = torch.eye(10000).to(gpu)
y1 = torch.eye(10000).to(gpu)
z1 = x1.mm(y1).to(cpu)  

CPU times: user 712 ms, sys: 517 ms, total: 1.23 s
Wall time: 1.23 s
